export const routes = {
  auth: {
    Initial: 'Initial',
    RegisterDevice: 'RegisterDevice',
    SignUp: 'SignUp',
    SignIn: 'SignIn',
    SetupPIN: 'SetupPIN',
    LoginPIN: 'LoginPIN',
  },
  navigators: {
    Sunrise: 'SunriseNavigator',
    TokenSale: 'TokenSaleNavigator',
    Sollar: 'SollarNavigator',
    Shop: 'ShopNavigator',
    Profile: 'ProfileNavigator',
  },
  tabs: {
    Transfers: 'Transfers',
    Sunrise: 'Sunrise',
    Settings: 'Settings',
    AmirInvest: 'AmirInvest',
    AmirWallet: 'AmirWallet',
    AmirFinance: 'AmirFinance',
  },
  homeTab: {
    CryptoWallet: 'CryptoWallet',
    Saving: 'Saving',
    SavingTxHistory: 'SavingTxHistory',
    Profile: 'ProfileTab',
  },
  sunriseTab: {
    program: 'SunriseProgram',
    loyaltyLanding: 'LoyaltyLandingScreen',
    discountHistory: 'DiscountHistoryScreen',
    landing: 'SunriseLandingScreen',
    ambassadorLanding: 'AmbassadorLandingScreen',
    ambassadorActivity: 'AmbassadorActivity',
    partner: 'SunrisePartner',
    line: 'SunriseLineScreen',
  },
  amirInvest: {
    Empty: '-',
  },
  amirWallet: {
    Accounts: 'Accounts',
    CryptoWallet: 'CryptoWallet',
    CryptoWalletTxHistory: 'CryptoWalletTxHistory',
    SollarNavigator: 'SollarNavigator',
    ShopNavigator: 'ShopNavigator',
  },
  amirFinance: {
    Accounts: 'Accounts',
    Saving: 'Saving',
    StableCreate: 'StableCreate',
    Stable: 'Stable',
    StableAllAccounts: 'StableAllAccounts',
    RequestHistory: 'RequestHistory',
    StableAllClosedAccounts: 'StableAllClosedAccounts',
    SavingTxHistory: 'SavingTxHistory',
  },
  transfers: {
    TransferMenu: 'TransferMenu',
    TransferConversion: 'TransferConversion',
    TransferToSaving: 'TransferToSaving',
    TransferFromSaving: 'TransferFromSaving',
    TransferByEmail: 'TransferByEmail',
    TransferByPhone: 'TransferByPhone',
    Deposit: 'Deposit',
    Withdraw: 'Withdraw',
    //CheckFace: 'GlobalPassBioScreen',
  },
  sollarNav: {
    SollarWallet: 'SollarWallet',
    SollarWalletBuy: 'SollarWalletBuy',
    SollarWalletTxHistory: 'SollarWalletTxHistory',
  },
  tokenSaleNav: {
    TokenSale: 'TokenSale',
    TokenSaleOfferDetails: 'TokenSaleOfferDetails',
    TokenSaleWallet: 'TokenSaleWallet',
    TokenSaleBuy: 'TokenSaleBuy',
    TokenSaleEdit: 'TokenSaleEdit',
    TokenSaleEditChoice: 'TokenSaleEditChoice',
  },
  shopNav: {
    ShopList: 'ShopList',
    ShopProduct: 'ShopProduct',
    ShopFilters: 'ShopFilters',
    ShopHistory: 'ShopHistory',
    ShopBasket: 'ShopBasket',
    ShopCheckout: 'ShopCheckout',
    ShopFavourites: 'ShopFavourites',
    ShopOrderDetails: 'ShopOrderDetails',
    ShopSort: 'ShopSort',
  },
  profileTab: {
    profileMenu: 'ProfileMenu',
    socialNetworks: 'SocialNetworksScreen',
    aboutApp: 'AboutApp',
    changeEmail: 'ChangeEmail',
    changePassword: 'ChangePassword',
    reinvestmentSettings: 'ReinvestmentSettings',
    twoFactorAuthSettings: 'TwoFactorAuthSettings',
    kycScreen: 'KYCScreen',
    languageSettings: 'LanguageSettings',
    deleteAccount: 'DeleteAccount',
    //PassKyc: 'GlobalPassKycScreen',
  },
};
