/* eslint-disable camelcase */

export const userInitialValues = {
  allow_show_contacts: true,
  ambassador_agree: true,
  ambassador_level: 0,
  balance_tour_passed: true,
  bonus_status: null,
  disabled_refferal_lines: [],
  email_is_verified: true,
  email: '',
  in_bonus_action: null,
  is_admin: false,
  is_ambassador: true,
  is_amir_cell_support: false,
  is_google_enabled: true,
  is_mailer: false,
  is_reinvest: false,
  is_super_admin: false,
  is_support: false,
  is_verified: true,
  is_verifier: false,
  last_status_change: '',
  last_status: 'brilliant',
  level: 0,
  name: '',
  parent_name: '',
  phone_is_verified: false,
  phone: '+7',
  ref_tour_passed: null,
  refferal_agree: true,
  refferal: '',
  role_id: null,
  role: null,
  shop_agree: false,
  showKycBanner: false,
  sunrise_agree: false,
  twofa_error_reason: null,
  twofa_status: null,
  twofa_type: null,
  reinvestment: {
    savings: {
      btc: 0,
      eth: 0,
      usdt: 0,
    },
    stable: 0,
    partner: 0,
  },
  loyalty_programs: {
    default: {
      level: 0,
      joined: false,
      status_date: 'Mon, 18 Oct 2021 13:18:17 GMT',
    },
    sunrise: {
      level: 0,
      joined: true,
      available: true,
      status_date: 'Mon, 18 Oct 2021 13:18:17 GMT',
    },
    ambassador: {
      level: 0,
      joined: true,
      status_date: 'Mon, 18 Oct 2021 13:18:17 GMT',
    },
  },
  kycStatus: {
    status: null,
  },
  course: {
    bitcoin_btc: '1.0',
    bitcoin_eth: '14.64986815118663932025',
    bitcoin_usdt: '60745.64',
    bitcoin_usd: '60745.64',
    ethereum_btc: '0.06826',
    ethereum_eth: '1.0',
    ethereum_usdt: '4146.43',
    ethereum_usd: '4146.43',
  },
  fee: {
    bitcoin: '0',
    ethereum: '0',
    usdt: '0',
  },
};

export const userInitialValuesV2 = {
  allow_show_contacts: false,
  ambassador_agree: false,
  ambassador_level: 0,
  bonus_status: null,
  disabled_refferal_lines: [],
  email_is_verified: false,
  email: '',
  in_bonus_action: null,
  is_admin: false,
  is_ambassador: false,
  is_amir_cell_support: false,
  is_google_enabled: false,
  is_mailer: false,
  is_reinvest: false,
  is_super_admin: false,
  is_support: false,
  is_verified: false,
  is_verifier: false,
  last_status_change: '',
  last_status: '',
  level: 0,
  name: '',
  parent_name: '',
  phone_is_verified: false,
  phone: '',
  refferal_agree: false,
  refferal: '',
  role_id: null,
  role: null,
  shop_agree: false,
  sunrise_agree: false,
  twofa_error_reason: null,
  twofa_status: null,
  twofa_type: null,
  reinvestment: {
    savings: {
      btc: 0,
      eth: 0,
      usdt: 0,
    },
    stable: 0,
    partner: 0,
  },
  loyalty_programs: {
    default: {
      joined: false,
      level: 0,
      status_date: '',
    },
    sunrise: {
      available: false,
      joined: false,
      level: 0,
      status_date: '',
    },
    ambassador: {
      can_request: false,
      joined: false,
      level: 0,
      status_date: '',
    },
  },
};
