import env from 'react-native-config';

export const {
  API_VERSION,
  API_HOST,
  IS_PRODUCTION,
  RECAPTCHA_KEY,
  RECAPTCHA_KEY_TEST,
  RECAPTCHA_HOST,
  SENTRY_DSN,
  GLOBALPASS_URL,
  GLOBALPASS_KYC,
  GLOBALPASS_BIO,
  TEST_ACCOUNT_EMAIL,
  TEST_ACCOUNT_CODE,
  REFERRAL_LINKS_HOST_OLD,
  REFERRAL_LINKS_HOST_NEW,
  YOUTUBE_CONTACT,
  TELEGRAM_CONTACT_EN,
  TELEGRAM_CONTACT_RU,
  INSTAGRAM_CONTACT_EN,
  INSTAGRAM_CONTACT_RU,
  TWITTER_CONTACT,
  TIKTOK_CONTACT,
  FAQ_RU,
  FAQ_EN,
  SHOP_AGREE_RU,
  SUNRISE_AGREE_RU,
} = env;

export default env;
